### ISSUE TITLE
Vibrato (modulation) waveform is Sawtooth

### ISSUE THREAD

**Issue by DevanWolf** [M-HT/casio_sw-10#2]
That is not accurate. On the GZ-70SP (even emulated on MAME) the waveform is correctly Sine. There needs to be a new version that uses the correct waveform.

**Comment by M-HT** [comment]
First there doesn't **need** to be anything. Second this project is about SW-10, so it's irrelevant what GZ-70SP does differently (even if they use the same ROM).
