### ISSUE TITLE
expansion of available settings?

### ISSUE THREAD

**Issue by Davedson-debug** [M-HT/casio_sw-10#3]
since this is a decompilation project, i will take a wild guess that it's now possible to modify it, isn't it possible to expand available settings? (bigger polyphony, bit depth, bigger sample rate, etc.)

**Comment by M-HT** [comment]
In theory yes, but what would be the point ?
And who would do it, because I don't have any interest in doing it ?

**Comment by Davedson-debug** [comment]
Now that's a good question, mostly to get better output quality, and i think that i even know someone who might do that, no guarantees tho
