### ISSUE TITLE
about binary conversion (info request)

### ISSUE THREAD

**Issue by jariseon** [M-HT/casio_sw-10#4]
outstanding reversing work, and what a clever idea to manipulate the binary headers. do you think the vxd -> dll conversion procedure could be repeated for another win95-era vxd softsynth, or did the sw10 have something special which made that possible? ghidra seems to have a vxd loader but haven't tried that out yet.

**Comment by M-HT** [comment]
SW-10 didn't do anything special, so in theory similar thing could be done for other vxd's.

**Comment by jariseon** [comment]
cool, i started scratching my head already. many thanks! pls feel free to close the issue.
