### ISSUE TITLE
Decompilation requests

### ISSUE THREAD

**Issue by pachuco** [M-HT/casio_sw-10#5]
Do you take requests(perhaps paid) for decompiling midi synths?

**Comment by M-HT** [comment]
No, I don't. You can suggest a midi synth and I can take a look at it, but no guarantees of anything.

**Comment by pachuco** [comment]
Hurrrrr, lettuce see...

FMAudio
Older version: https://cdn.discordapp.com/attachments/639581629727113227/1031969620409720885/fmap-1.0.136.exe
Newer version: https://cdn.discordapp.com/attachments/639581629727113227/1031969620770439208/fpsetup.exe

Overview:
- circa early to mid 00s
- obscure software
- very broken midi handling
- so broken that even authors admit it indirectly(midi playback is halted when distorted guitar patch is loaded in new version)
- some improvements related to value interpolation in new version(Doom - Tower of Babel)
- it will ocasionally sound very nice
- unfortunatelly, I think it's written in C++

Render samples:
- https://cdn.discordapp.com/attachments/639581629727113227/1031967059145404416/crestest_mid_FMaudio.ogg
- https://cdn.discordapp.com/attachments/639581629727113227/1031967059602579566/008-Boss04_mid_FMaudio.ogg
- https://cdn.discordapp.com/attachments/639581629727113227/1031967059946516672/evocean_mid_FMaudio.ogg

And the cherry on the cake:
https://cdn.discordapp.com/attachments/639581629727113227/1031967133216800799/drunk_doom_FMaudio.ogg

**Comment by pachuco** [comment]
Come to think of it, I think only the soundbank saves this one. And maybe the reso lowpass filter.

**Comment by M-HT** [comment]
I took a look at it, but unfortunately I won't be able to do anything with this.

**Comment by DevanWolf** [comment]
Instead, can you please unpack [smpfull.fma](https://github.com/user-attachments/files/32178221/smpfull.fma.zip) , it's packed in PKWARE format (and it's not a ZIP).

**Comment by M-HT** [comment]
Here is a program which unpacks the file. You need some files (libdynamite.c and libdynamite.h) from [this project](https://github.com/twogood/dynamite) for decompression (,wav files are not compressed).

[unpack_fma.c](https://github.com/user-attachments/files/32254868/unpack_fma.c)

**Comment by pachuco** [comment]
I think most interesting thing here is the church organ patch, with its low rumble.
Also, all wavs have loop points.

**Comment by DevanWolf** [comment]
I'm trying to remake FMaudio as a soundfont, can you please help me identify the instrument data (split points, ADSR, etc.) in [defaults.fi3](https://github.com/user-attachments/files/32552658/defaults.fi3.zip)?

**Comment by M-HT** [comment]
Sorry, I don't  know how to do that.
