### ISSUE TITLE
Request: Step-by-step guide

### ISSUE THREAD

**Issue by pachuco** [M-HT/casio_sw-10#6]
What is workflow for creating conv2dll.c for our casio synth?
I see a lot of manual patching. Scary!

It would be nice to have step-by-step RE/patching process, to learn to apply on other VxDs.

**Comment by M-HT** [comment]
There's no exact process that can be applied to other VxDs.

Converting VxD to DLL means at the very least reading data from VxD, which is a `Linear executable` and writing data into DLL, which is a `Portable executable`.

What exactly to read and write (or add, remove, modify) depends on the VxD. You need to reverse engineer what the VxD is doing, what are its functions and parameters - either from the VxD or from other files which are calling functions in the VxD. You also need to handle your VxD calling functions in other VxDs.


Some information about VxDs is available [here](https://www-user.tu-chemnitz.de/~heha/vxd/vxd.htm).
